const BLACK = "#030209";
const WHITE = "#ffffff";
const PRIMARY_COLOR = "#E25EAB";
const SECONDARY_COLOR = "#9E4B7B";
const DARK_COLOR = "#0E0822";
const BACKGROUND_COLOR = "#352949";
const NEUTRAL_COLOR = "#BEC7E2";
const NEUTRAL_COLOR_DARK = "#4D3F53";
const THIRD_COLOR = "#000000";

export const COLORS = {
  BLACK,
  WHITE,
  PRIMARY_COLOR,
  SECONDARY_COLOR,
  BACKGROUND_COLOR,
  NEUTRAL_COLOR,
  NEUTRAL_COLOR_DARK,
  THIRD_COLOR,
  DARK_COLOR,
};
