const BLACK = "#000000";
const WHITE = "#ffffff";
const PRIMARY_COLOR = "#5F34F7";
const SECONDARY_COLOR = "#111F58";
const BACKGROUND_COLOR = "#4F5057";
const NEUTRAL_COLOR = "#BEC7E2";
const NEUTRAL_COLOR_DARK = "#7D8CB4";
const THIRD_COLOR = "#EE571D";

export const COLORS = {
  BLACK,
  WHITE,
  PRIMARY_COLOR,
  SECONDARY_COLOR,
  BACKGROUND_COLOR,
  NEUTRAL_COLOR,
  NEUTRAL_COLOR_DARK,
  THIRD_COLOR,
};
